// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVG70FIuSDIyGHXDyuMEpiacL7URsyIEg',
    appId: '1:303460523060:android:9861563f7628fe77f43e61',
    messagingSenderId: '303460523060',
    projectId: 'cinezone-6b2d6',
    databaseURL: 'https://cinezone-6b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinezone-6b2d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJt9jKJK80O9qYJfPsExk6b3hdIvB76ME',
    appId: '1:303460523060:ios:41d3bcefae0a4a62f43e61',
    messagingSenderId: '303460523060',
    projectId: 'cinezone-6b2d6',
    databaseURL: 'https://cinezone-6b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinezone-6b2d6.firebasestorage.app',
    iosBundleId: 'com.example.projectTeam',
  );
}
